version: '3.8'

services:
  h265-video-generator:
    build: ./h265-video-generator
    image: h265-video-generator
    network_mode: host
    command: "ffmpeg -t 30 -f lavfi -i testsrc=size=1920x1080:rate=30 -map 0:v:0 -c:v libx265 -crf 28 -f rtp rtp://localhost:7000"
  
  gstreamer-h265-to-webrtc:
    image: restreamio/gstreamer:x86_64-latest-dev-with-source
    network_mode: host
    environment:
      - DISPLAY=$DISAPLAY
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - ~/.Xauthority:/root/.Xauthority
    command: 'gst-launch-1.0 udpsrc port=6000 caps = "application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96" ! rtph264depay ! avdec_h264 ! videoconvert ! queue ! video/x-raw, format=YUY2 ! jpegenc ! rtpjpegpay ! udpsink host=localhsot port=5000'
  
  ffmpeg_video_server:
    build: ./h265-video-server/ffmpeg-videoserver
    image: ffmpeg-videoserver
    network_mode: host
    command: "ffmpeg -protocol_whitelist file,udp,rtp -i session.sdp -payload_type 96 -c:v libx264 -crf 28 -f rtp rtp://localhost:6000"
  
  fastapi-videoserver:
    build: ./h265-video-server/fastapi-videoserver
    image: fastapi-videoserver
    network_mode: host
    volumes:
      - /home/ben/Downloads/:/from-host
    command: "uvicorn fastapi-videoserver.or-main:app --port 8080"
  
  streaming-app:
    build: ./video-streaming-app
    image: streaming-app
    network_mode: host
    volumes:
      - ./video-streaming-app:/app
    command: "./install_and_run.sh"
