version: '3.8'

services:
  h265-video-generator:
    build: .
    network_mode: host
    command: "ffmpeg -t 10 -f lavfi -i testsrc=size=1920x1080:rate=30 -c:v libx265 -crf 28 -f rtp rtp://localhost:6000"
  h265-video-player:
    build: .
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: "/usr/bin/firefox"
